dh_type: "Modified"

dh_params:
  a:          [0.0, 0.0,    0.0,    0.0825, -0.0825, 0.0,   0.088, 0.0]
  alpha:      [0, -1.570796, 1.570796, 1.570796, -1.570796, 1.570796, 1.570796, 0.0]
  d:          [0.333, 0.0, 0.316, 0.0, 0.384, 0.0, 0.0, 0.107]
  theta_bias: [0, 0, 0, 0, 0, 0, 0, -0.785398]

  radii:
    [0.125, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1,
     0.1, 0.1, 0.05, 0.05, 0.075, 0.075, 0.075, 
     0.075, 0.08, 0.08]

  # radii:
  #   [0.10, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1,
  #    0.1, 0.1, 0.05, 0.05, 0.05, 0.05, 0.05, 
  #    0.05, 0.05, 0.05]

  frames:
    [0, 0, 1, 1, 2, 2, 3, 3, 4, 4,
     4, 4, 4, 4, 6, 6, 7, 7]

  centers:
    - [ -0.03,  0.0,  -0.3]
    - [ 0.0,  0.0,  -0.15]
    - [ 0.0,  0.0,  -0.07]
    - [ 0.0,  0.0,   0.07]
    - [ 0.0,  0.0,  -0.075]
    - [ 0.0,  0.0,  -0.175]
    - [ 0.0,  0.0,  -0.05]
    - [ 0.0,  0.0,   0.05]
    - [ 0.0,  0.0,  -0.3]
    - [ 0.0,  0.0,  -0.2]
    - [ 0.0,  0.08, -0.125]
    - [ 0.0,  0.09, -0.075]
    - [ 0.0,  0.075,  0.00]
    - [ 0.0,  -0.015,  0.00]
    - [ 0.0,  0.0,  -0.04]
    - [ 0.0,  0.0,  0.04]
    - [ 0.0,  0.05,   0.03]
    - [ 0.0,  -0.05,  0.03]

# body_frames:
#   - frame_id: B1
#     position: [0.0, 0.0, 0.0]
#     orientation: [0.0, 0.0, 0.0, 1.0] # quaternion (qx, qy, qz, qw)
#     monitor_topic: "/B1_pose"
#     box:
#       name: sdf_box_1
#       center: [0.120, -0.300, 0.050]    # [x, y, z] in metres (wrt frame B)
#       orientation: [0.0, 0.0, 0.0, 1.0] # quaternion (qx, qy, qz, qw)
#       size: [ 18, 18, 38 ]
#   - frame_id: B2
#     position: [0.0, 0.0, 0.0]
#     orientation: [0.0, 0.0, 0.0, 1.0] # quaternion (qx, qy, qz, qw)
#     monitor_topic: "/B2_pose"
#     box:
#       name: sdf_box_2
#       center: [0.420,  0.170, 0.050]
#       orientation: [0.0,   0.0,   0.0, 1.0]
#       size: [ 58, 58, 2 ]


